# v2 sintax
version: '2'

services:

  # node 10
  node:
    build: ./
    container_name: contacts-api-node
    restart: always
    ports:
      - "3333:3333"
    links:
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  web:
    image: nginx:latest
    container_name: contacts-api-nginx
    ports:
      - "80:80"
    volumes_from:
      - node
    volumes:
      - ./default.conf/:/etc/nginx/conf.d/default.conf
    links:
      - node
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
