# v2 sintax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  contacts-api-mysql-data:
    driver: local
  # Redis Data
  contacts-api-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: contacts-api-mysql
    volumes:
      - contacts-api-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=contactsapi
      - MYSQL_DATABASE=contactsapi
      - MYSQL_USER=contactsapi
      - MYSQL_PASSWORD=contactsapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # node 10
  node:
    build: ./node/
    container_name: contacts-api-node
    restart: always
    ports:
      - "3333:3333"
    links:
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  web:
    image: nginx:latest
    container_name: contacts-api-nginx
    ports:
      - "80:80"
    volumes_from:
      - node
    volumes:
      - ./default.conf/:/etc/nginx/conf.d/default.conf
    links:
      - node
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
